import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { Header } from "@/shared/components/header";
import { EditorProvider } from "@/shared/components/editor-provider";
import { descriptor } from "@/data/clocks/jocker/descriptor";

const onest = Onest({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onest.className} bg-black flex flex-col  text-white h-screen w-full`}
      >
        <Header />
        <EditorProvider descriptor={descriptor}>{children}</EditorProvider>
      </body>
    </html>
  );
}
